### PR TITLE
Show progress bar in `propagate`

### PR DESCRIPTION
**Pull request by RemiLehe**
The `propagate` function can potentially take a long time (if the grid is large) ; this PR changes the code so that the `propagate` function shows the progress bar:

Screenshot 2023-10-20 at 12 08 27 PM

### CODE REVIEW

**Review by hightower8083 — COMMENTED** [review]
looks good to me, but one little question: could you check how this will look in methods with many propagations, e.g. `gerchberg_saxton_algo`. I'd imagine having many tens of dead bars might appear bit ugly, so an option to turn them off might be helpful.

**Comment by RemiLehe** [comment]
Ok, sounds good. I have made the progress bar optional and turned it off in the Gerschberg-Saxton function.

**Review by hightower8083 — APPROVED** [review]
looks good!

**Review by hightower8083 — APPROVED** [review]

**Review by hightower8083 — APPROVED** [review]
.

**Pull request merged**
